import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const dreamSparks = localFont({
  src: "./fonts/DreamSparks.ttf",  
  variable: "--font-dream-sparks",  
  weight: "400",
});

const bebasNeue = localFont({
  src: "./fonts/BebasNeue.ttf",
  variable: "--font-bebas-neue",
  weight: "400",
})

const Inter = localFont({
  src: "./fonts/Inter.ttf",
  variable: "--font-inter",
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dreamSparks.variable} ${bebasNeue.variable} ${Inter.variable} antialiased `}
      >
        {children}
      </body>
    </html>
  );
}
